server:
  port: 8082

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full

spring:
  jackson:
    default-property-inclusion: non_null

faireservice:
  url: http://www.faire-stage.com

logging.level.com.faire: debug